# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/client"
    schedule:
      interval: "weekly"
    labels:
      - "frontend dependency update"
    open-pull-requests-limit: 10
    reviewers:
      - spencerlepine
      
  - package-ecosystem: "npm"
    directory: "/apps/gateway"
    schedule:
      interval: "weekly"
    labels:
      - "gateway API dependency update"
    open-pull-requests-limit: 10
    reviewers:
      - spencerlepine
      
  - package-ecosystem: "npm"
    directory: "/apps/orders"
    schedule:
      interval: "weekly"
    labels:
      - "orders API dependency update"
    open-pull-requests-limit: 10
    reviewers:
      - spencerlepine
      
  - package-ecosystem: "npm"
    directory: "/apps/users"
    schedule:
      interval: "weekly"
    labels:
      - "users API dependency update"
    open-pull-requests-limit: 10
    reviewers:
      - spencerlepine

  - package-ecosystem: "npm"
    directory: "/apps/products"
    schedule:
      interval: "weekly"
    labels:
      - "products API dependency update"
    open-pull-requests-limit: 10
    reviewers:
      - spencerlepine
      