apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gatewayapi
  name: gatewayapi
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gatewayapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gatewayapi
    spec:
      containers:
      - image: gateway
        name: gateway
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 3000
status: {}