version: '3.9'

services:
  gateway:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      USERS_API_URL: http://localhost:8001
      ORDERS_API_URL: http://localhost:8002
      PRODUCTS_API_URL: http://localhost:8003