version: '3.9'

services:
  mysql_db:
    networks:
      - mysql-network
    platform: linux/x86_64 # M1 Chip fix
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'root' BROKEN
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - user-db:/var/lib/mysql

  users:
    networks:
      - web
      - mysql-network
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      PORT: '8001'
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: '12345'
      DATABASE_NAME: testdb
      DATABASE_DIALECT: mysql
      NODE_ENV: production


# Persist the database
volumes:
  user-db:

networks:
  web:
  mysql-network: