# kubectl apply -f nodekube/hello-world-service-def.yaml
apiVersion: v1
kind: Service
metadata:
    name: helloworld-service
spec:
    type: NodePort
    ports:
        - targetPort: 5000
          port: 80
          nodePort: 30001
    selector:
        release: beta
        type: poc