# kubectl apply -f nodekube/hello-world-deployment-def.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    release: beta
    type: poc
  name: helloworld-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      type: poc
  template:
    metadata:
      labels:
        release: beta
        type: poc
      name: helloworld-pod
    spec:
      containers:
        - image: "gateway"
          name: gateway-container
          ports:
            - containerPort: 5000