version: '3.9'

services:
  # cassandra_db:
  #   networks:
  #     - cassandra-network
  #   image: cassandra:3.11.2
  #   restart: always
  #   ports:
  #     - 9042:9042
  #   environment:
  #     - "MAX_HEAP_SIZE=256M"
  #     - "HEAP_NEWSIZE=128M"
  #   volumes:
  #     - products-db:/var/lib/cassandra
  #   healthcheck:
  #     test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
  #     interval: 15s
  #     timeout: 10s
  #     retries: 10
  cassandra_db:
    networks:
      - cassandra-network
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    networks:
      - cassandra-network
    image: cassandra:3.11.2
    depends_on:
      cassandra_db:
        condition: service_healthy
    volumes:
      - ./src/models/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra_db -f /schema.cql --debug" # -u user -p pass

  products:
    networks:
      - web
      - cassandra-network
    depends_on:
      - cassandra-load-keyspace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      PORT: '8002'
      CASSANDRA_HOST: cassandra_db
      CASSANDRA_DATACENTER: datacenter1
      CASSANDRA_KEYSPACE: mykeyspace
      CASSANDRA_USER: my_user
      CASSANDRA_PASSWORD: my_password
      CASSANDRA_PORT: '9042'

# Persist the database
volumes:
  products-db:

networks:
  web:
  cassandra-network: