# The following is an example of a Deployment. It creates a ReplicaSet to bring up three nginx Pods:
# A Deployment named nginx-deployment is created, indicated by the .metadata.name field.
# The Deployment creates three replicated Pods, indicated by the .spec.replicas field.

# kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml
# kubectl get deployments
# kubectl scale deployment/nginx-deployment --replicas=10

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80