version: '3.9'

services:
  users:
    build: .
    ports:
      - 8002:8002
    environment:
      PORT: 8002
      CASSANDRA_HOST: 127.0.0.1
      CASSANDRA_DATACENTER: datacenter1
      CASSANDRA_KEYSPACE: mykeyspace
      CASSANDRA_USER: my_user
      CASSANDRA_PASSWORD: my_password
      CASSANDRA_PORT: 9042
