version: '3.9'

services:
  cassandra_db:
    networks:
      - cassandra-network
    image: cassandra:3.11.2
    restart: always
    ports:
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - products-db:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  products:
    networks:
      - web
      - cassandra-network
    depends_on:
      - cassandra_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      PORT: '8002'
      CASSANDRA_HOST: cassandra_db
      CASSANDRA_DATACENTER: datacenter1
      CASSANDRA_KEYSPACE: mykeyspace
      CASSANDRA_USER: my_user
      CASSANDRA_PASSWORD: my_password
      CASSANDRA_PORT: '9042'

# Persist the database
volumes:
  products-db:

networks:
  web:
  cassandra-network: