version: '3.9'

services:
  users:
    build: .
    ports:
      - 8001:8001
    environment:
      PORT: 8001
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: testdb
      DATABASE_DIALECT: mysql
      NODE_ENV: production
