name: Branch CI

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Continuous Integration Workflow
#  Author: @spencerlepine
#
#  Features
#    - lint, test, and build (w/ Docker)
#    - output test coverage to artifact
#    - comment test coverage on pull request
#    - run CI for each microservice
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

on:
  pull_request:
    branches:
      - '*'

jobs:
  # -- Gateway Microservice --------------------
  gateway_ci:
    name: "🧪 Node CI"
    uses: ./.github/workflows/node_ci.yml
    with:
      folder_name: gateway

  gateway_coverage:
    needs: [gateway_ci]
    runs-on: ubuntu-latest
    env:
      service: 'gateway'

    name: "🎉 Coverage Report"
    steps:
      - name: Download Test Covereage Output
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.service }}-code-coverage-report-${{ github.sha }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: gateway
          recreate: true
          path: ${{ env.service }}-code-coverage-results.md

  # -- Users Microservice --------------------
  users_ci:
    name: "🧪 Node CI"
    uses: ./.github/workflows/node_ci.yml
    with:
      folder_name: users

  users_coverage:
    needs: [users_ci]
    runs-on: ubuntu-latest
    env:
      service: 'users'

    name: "🎉 Coverage Report"
    steps:
      - name: Download Test Covereage Output
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.service }}-code-coverage-report-${{ github.sha }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: users
          recreate: true
          path: ${{ env.service }}-code-coverage-results.md

  # -- Products Microservice --------------------
  products_ci:
    name: "🧪 Node CI"
    uses: ./.github/workflows/node_ci.yml
    with:
      folder_name: products

  products_coverage:
    needs: [products_ci]
    runs-on: ubuntu-latest
    env:
      service: 'products'

    name: "🎉 Coverage Report"
    steps:
      - name: Download Test Covereage Output
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.service }}-code-coverage-report-${{ github.sha }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: products
          recreate: true
          path: ${{ env.service }}-code-coverage-results.md