name: End-to-End
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:

  end-to-end-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'electron', 'microsoft-edge']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start the Docker Containers
        run: docker-compose up -d
         
      - name: Cypress info
        uses: cypress-io/github-action@v4
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress info
          working-directory: ./apps/__tests__
          browser: ${{ matrix.browser }}
          wait-on: http://localhost:3000

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: screenshots-in-chrome
      #     path: ./apps/__tests__cypress/screenshots

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: video-in-chrome
      #     path: ./apps/__tests__cypress/videos

      # - run: npx image-size cypress/screenshots/**/*.png
      #   working-directory: ./apps/__tests__

      # # I wonder if GH Actions VM includes any of the tools that
      # # can tell us the resolution of a video file
      # - run: ffprobe cypress/videos/*.mp4 || true
      # - run: mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true
